# Project information
site_name: "Digital Development Documentation"
site_description: "Digital Development"
site_author: "bobsterjs"
site_url: "https://docs.digitaldev.bobsterjs.ml/"

# Copyright
copyright: "&copy; 2022 Digital Development & BobsterJS"

# Repository
repo_name: "bobstersok/digital-dev-docs"
repo_url: "https://github.com/bobstersok/digital-dev-docs"
edit_uri: "https://github.com/bobstersok/digital-dev-docs/edit/main/docs"

# Configuration
docs_dir: "docs"
theme:
  name: "material"
  language: "en"
  shortcuts:
    help: 191 # ?
    next: 78 # n
    previous: 80 # p
    search: 83 # s
  palette:
    primary: "orange"
    accent: "green"
  features:
    - tabs
  font:
    text: 'Poppins'
  #code: 'Ubuntu Mono'
  #icon:
  #logo: 'images/logo.svg'
  #favicon: 'assets/images/favicon.ico'

# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - mdx_math:
      enable_dollar_delimiter: true
  - toc:
      permalink: true
      separator: "_"

plugins:
  - search:
      separator: '[\s\-\.]+'
      lang:
        - en

# Customization
extra_javascript:
  - "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js?config=TeX-MML-AM_CHTML"
extra_css:
  - "assets/css/custom.css"
extra:
  manifest: "manifest.json"
  social:
    - icon: "fontawesome/brands/github-alt"
      link: "https://github.com/peaceiris"
    - icon: "fontawesome/brands/twitter"
      link: "https://twitter.com/piris314en"

# Page tree
nav:
  - "Home": "index.md"
  - "Products":
      - "Ambulance Tail Lift": "ambulance/taillift.md"
      - "BVM Tool": "ambulance/bvm.md"
      - "Ambulance Kit Placer": "ambulance/ambulancekit.md"
      - "MDT System":
        - "Setup The MDT": "ambulance/mdt/setup-mdt.md"
        - "Using The MDT": "ambulance/mdt/using-mdt.md"
